#!/bin/bash

# Setup ngrok tunnels for AI models in production
# Usage: ./scripts/setup-tunnels.sh

set -e

echo "🌐 Setting up AI Model Tunnels for PetCanvas"
echo "=============================================="

# Check if ngrok is installed
if ! command -v ngrok &> /dev/null; then
    echo "❌ ngrok not found. Please install it first:"
    echo "   brew install ngrok  # macOS"
    echo "   # or download from https://ngrok.com/download"
    exit 1
fi

# Check if AI services are running
echo "🔍 Checking if AI services are running..."

# Check A1111
if curl -s http://localhost:7860/sdapi/v1/sd-models &> /dev/null; then
    echo "✅ Stable Diffusion WebUI (A1111) is running on port 7860"
    A1111_RUNNING=true
else
    echo "⚠️  Stable Diffusion WebUI (A1111) not detected on port 7860"
    A1111_RUNNING=false
fi

# Check ComfyUI
if curl -s http://localhost:8188/api/prompt &> /dev/null; then
    echo "✅ ComfyUI is running on port 8188"
    COMFYUI_RUNNING=true
else
    echo "⚠️  ComfyUI not detected on port 8188"
    COMFYUI_RUNNING=false
fi

if [ "$A1111_RUNNING" = false ] && [ "$COMFYUI_RUNNING" = false ]; then
    echo ""
    echo "❌ No AI services detected. Please start them first:"
    echo ""
    echo "🔥 To start Stable Diffusion WebUI:"
    echo "   cd /path/to/stable-diffusion-webui"
    echo "   ./webui.sh --api"
    echo ""
    echo "🔥 To start ComfyUI:"
    echo "   cd /path/to/ComfyUI"
    echo "   python main.py"
    echo ""
    exit 1
fi

# Create tunnel configuration
echo "📝 Creating tunnel configuration..."

# Generate unique subdomain suffix
SUFFIX=$(date +%m%d)
A1111_SUBDOMAIN="petcanvas-a1111-$SUFFIX"
COMFYUI_SUBDOMAIN="petcanvas-comfyui-$SUFFIX"

# Create ngrok config file
mkdir -p ~/.ngrok2
cat > ~/.ngrok2/petcanvas.yml << EOF
version: '2'
authtoken: ${NGROK_AUTH_TOKEN}
tunnels:
EOF

if [ "$A1111_RUNNING" = true ]; then
    cat >> ~/.ngrok2/petcanvas.yml << EOF
  a1111:
    proto: http
    addr: 7860
    subdomain: $A1111_SUBDOMAIN
    inspect: false
    bind_tls: true
EOF
fi

if [ "$COMFYUI_RUNNING" = true ]; then
    cat >> ~/.ngrok2/petcanvas.yml << EOF
  comfyui:
    proto: http
    addr: 8188
    subdomain: $COMFYUI_SUBDOMAIN
    inspect: false
    bind_tls: true
EOF
fi

# Start tunnels in background
echo "🚀 Starting tunnels..."

if [ "$A1111_RUNNING" = true ]; then
    echo "🔗 Starting A1111 tunnel..."
    nohup ngrok start --config ~/.ngrok2/petcanvas.yml a1111 > /tmp/ngrok-a1111.log 2>&1 &
    A1111_PID=$!
    sleep 3
    A1111_URL="https://$A1111_SUBDOMAIN.ngrok.io"
    echo "   A1111 tunnel: $A1111_URL"
fi

if [ "$COMFYUI_RUNNING" = true ]; then
    echo "🔗 Starting ComfyUI tunnel..."
    nohup ngrok start --config ~/.ngrok2/petcanvas.yml comfyui > /tmp/ngrok-comfyui.log 2>&1 &
    COMFYUI_PID=$!
    sleep 3
    COMFYUI_URL="https://$COMFYUI_SUBDOMAIN.ngrok.io"
    echo "   ComfyUI tunnel: $COMFYUI_URL"
fi

# Test tunnel connectivity
echo ""
echo "🧪 Testing tunnel connectivity..."

if [ "$A1111_RUNNING" = true ]; then
    if curl -s "$A1111_URL/sdapi/v1/sd-models" &> /dev/null; then
        echo "✅ A1111 tunnel is working"
    else
        echo "❌ A1111 tunnel test failed"
    fi
fi

if [ "$COMFYUI_RUNNING" = true ]; then
    if curl -s "$COMFYUI_URL/api/prompt" &> /dev/null; then
        echo "✅ ComfyUI tunnel is working"
    else
        echo "❌ ComfyUI tunnel test failed"
    fi
fi

# Create environment file for production
echo ""
echo "📝 Creating production environment file..."
cat > .env.production << EOF
# Generated by setup-tunnels.sh on $(date)
NEXT_PUBLIC_GA_MEASUREMENT_ID=G-XXXXXXXXXX
NEXT_PUBLIC_SITE_URL=https://petcanvas.vercel.app
EOF

if [ "$A1111_RUNNING" = true ]; then
    echo "A1111_BASE_URL=$A1111_URL" >> .env.production
fi

if [ "$COMFYUI_RUNNING" = true ]; then
    echo "COMFYUI_BASE_URL=$COMFYUI_URL" >> .env.production
fi

echo "USE_CLOUD_FALLBACK=true" >> .env.production

# Save tunnel info
cat > tunnel-info.json << EOF
{
  "timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "tunnels": {
EOF

if [ "$A1111_RUNNING" = true ]; then
    cat >> tunnel-info.json << EOF
    "a1111": {
      "url": "$A1111_URL",
      "local_port": 7860,
      "pid": $A1111_PID,
      "subdomain": "$A1111_SUBDOMAIN"
    }
EOF
    if [ "$COMFYUI_RUNNING" = true ]; then
        echo "," >> tunnel-info.json
    fi
fi

if [ "$COMFYUI_RUNNING" = true ]; then
    cat >> tunnel-info.json << EOF
    "comfyui": {
      "url": "$COMFYUI_URL",
      "local_port": 8188,
      "pid": $COMFYUI_PID,
      "subdomain": "$COMFYUI_SUBDOMAIN"
    }
EOF
fi

cat >> tunnel-info.json << EOF
  }
}
EOF

# Display summary
echo ""
echo "=============================================="
echo "🎉 Tunnel Setup Complete!"
echo ""
echo "📋 GitHub Secrets to Set:"
if [ "$A1111_RUNNING" = true ]; then
    echo "   A1111_BASE_URL = $A1111_URL"
fi
if [ "$COMFYUI_RUNNING" = true ]; then
    echo "   COMFYUI_BASE_URL = $COMFYUI_URL"
fi
echo ""
echo "🔧 Next Steps:"
echo "1. Update your GitHub repository secrets with the URLs above"
echo "2. Deploy using: ./scripts/deploy-vercel.sh production"
echo "3. Keep this terminal open to maintain tunnels"
echo ""
echo "📝 Configuration saved to:"
echo "   .env.production"
echo "   tunnel-info.json"
echo ""
echo "🛑 To stop tunnels:"
if [ "$A1111_RUNNING" = true ]; then
    echo "   kill $A1111_PID  # Stop A1111 tunnel"
fi
if [ "$COMFYUI_RUNNING" = true ]; then
    echo "   kill $COMFYUI_PID  # Stop ComfyUI tunnel"
fi
echo "=============================================="

# Keep script running to maintain tunnels
echo "🔄 Keeping tunnels alive... Press Ctrl+C to stop"
trap 'echo "🛑 Stopping tunnels..."; kill $A1111_PID $COMFYUI_PID 2>/dev/null; exit 0' INT
wait